export const ERRORS = {
  BAD_REQUEST: {
    LABOR_ALREADY_IN_PROGRESS: 'LABOR_ALREADY_IN_PROGRESS',
    LABOR_END_TIME_BEFORE_START_TIME: 'LABOR_END_TIME_BEFORE_START_TIME',
    LABOR_HAS_OVERLAP: 'LABOR_HAS_OVERLAP',
    LABOR_ON_FUTURE: 'LABOR_ON_FUTURE',
    INVALID_NEXT_STATUS: 'INVALID_NEXT_STATUS',
    INVALID_PREVIOUS_STATUS: 'INVALID_PREVIOUS_STATUS',
    CANNOT_COMPLETE_JOB_WITH_ON_GOING_SERVICE:
      'CANNOT_COMPLETE_JOB_WITH_ON_GOING_SERVICE',
    PART_MISSING_PRICE_VALUE: 'PART_MISSING_PRICE_VALUE',
    PART_MISSING_QUANTITY_VALUE: 'PART_MISSING_QUANTITY_VALUE',
    PART_MISSING_MARKUP_VALUE: 'PART_MISSING_MARKUP_VALUE',
  },
};
