name: PR Runner

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read
  packages: read
  pull-requests: read
  actions: write
  checks: write

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          # scope: 'write'
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST Tests
          path: packages/functions/tests/reports/*.xml
          reporter: jest-junit
          token: ${{ secrets.GITHUB_TOKEN }}
